# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20170929_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('signature', models.CharField(blank=True, max_length=200)),
                ('birth', models.DateTimeField(blank=True)),
                ('collections', models.ManyToManyField(to='collection.Website')),
                ('likes', models.ManyToManyField(to='article.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
