# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-collected']},
        ),
        migrations.RenameField(
            model_name='website',
            old_name='likes',
            new_name='collected',
        ),
    ]
