# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_post_mark_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mark_down',
            field=models.BooleanField(default=False),
        ),
    ]
